moss: Update to v0.26.6+git.42d4675
Fix a corner case where `moss sync -u` did not work, with the following
symptom when upgrading from the legacy config/repository format to the
new v0 config/repository format:

```
Error: sync: sync:
Package defined in system-model does not exist in any repository: (...)
```

In addition, improve trigger logging.

Signed-off-by: Rune Morling <ermo@aerynos.com>