virt-manager: Fix missing dependency pygobject
Installing virt-manager on a fairly new build of AerynOS resulted in
virt-manager crashing on launch. When run from the terminal, there was
an error:

```
 virt-manager
Traceback (most recent call last):
  File "/usr/bin/virt-manager", line 5, in <module>
    from virtManager import virtmanager
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 15, in
<module>
    gi.require_version("Gdk", "3.0")
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
```

Installing the `python-pygobject` package fixed this, as per this
comment on another project's issue with the same error:
https://github.com/enkore/i3pystatus/issues/314#issuecomment-180874574.